name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Build DatabasePlugin
#      run: cd src/DatabasePlugin/ && chmod +x gradlew && ./gradlew build && cd ../
#    - name: Build ExperiencePlugin
#      run: cd src/ExperiencePlugin/ && chmod +x gradlew && ./gradlew build && cd ../
#    - name: Build ModerationPlugin
#      run: cd src/ModerationPlugin/ && chmod +x gradlew && ./gradlew build && cd ../
#    - name: Build PollPlugin
#      run: cd src/PollPlugin/ && chmod +x gradlew && ./gradlew build && cd ../
    - name: Grant execute permission for gradlew
      run: cd src/ && chmod +x gradlew
    - name: Build with Gradle
      run: cd src/ && ./gradlew build
